### PR TITLE
Add Pandas call to show package versions of some packages

### PR DESCRIPTION
**Pull request by JonJala**

### CODE REVIEW

**Comment by ggoldman1** [comment]
Would it make sense to add asserts to check the versions of the packages on the user's end?

**Comment by JonJala** [comment]
We could do that.  If we want to go about that, there's no great way to
check versions on our own (it looks like Python 3.8 might have a nicer
way), though we could parse the Pandas return.

How confident are we that we know exactly what versions of imports are
absolutely required?  And are we confident enough to not even let things
try to run?

**Comment by ggoldman1** [comment]
I was just thinking somethign to the effect of reading in requirements.txt and then just checking each package version installed against what's in that file. Might be the case that other versions would get the job done but at least we could let the user know that their virtualenv isn't up?

**Comment by JonJala** [comment]
True, we could be a bit more proactive and indicate when there's a mismatch.  In this particular case, I wanted to add the information to the log so that when issues are submitted, we can check to see what versions of some of the packages they're using are (Pandas reports itself and its dependencies, I believe, which includes things like Numpy and Scipy, so we'd get the important ones, at least, along with the version of Python itself).

I think that a more explicit check and message is not a bad idea.  It just might take a little longer to implement than I was hoping this PR would take (even just comparing the Pandas output against the requirement.txt, but especially if we wanted to start comparing other packages as well).  We can capture it in our task list, though, so we don't forget / can make sure to get to it?

**Comment by ggoldman1** [comment]
Makes sense!

**Review by ggoldman1 — APPROVED** [review]

**Pull request merged**
